### ISSUE TITLE
Route fails with "Can't render headers after they are sent to the client."

### ISSUE THREAD

**Issue by s3u** [ql-io/ql.io#330]
The route on http://ql.io home page fails when the query is tokenized but search results turn out empty. The error is

error: Error: Can't render headers after they are sent to the client.
error: Error: Can't render headers after they are sent to the client.
   at ServerResponse.<anonymous> (http.js:565:11)
   at ServerResponse._renderHeaders (/home/abhishek/mine/apache/8282/
docs/qlio/qlgit/ql.io/modules/app/node_modules/express/node_modules/
connect/lib/patch.js:76:25)
   at ServerResponse.writeHead (http.js:827:20)
   at handleResponseCB (/home/abhishek/mine/apache/8282/docs/qlio/
qlgit/ql.io/modules/console/app.js:716:17)
   at EventEmitter.<anonymous> (/home/abhishek/mine/apache/8282/docs/
qlio/qlgit/ql.io/modules/console/app.js:264:36)
   at EventEmitter.emit (events.js:70:17)
   at /home/abhishek/mine/apache/8282/docs/qlio/qlgit/ql.io/modules/
engine/lib/engine.js:177:17
   at Object.cb (/home/abhishek/mine/apache/8282/docs/qlio/qlgit/
ql.io/modules/engine/lib/engine/log-emitter.js:84:24)
   at /home/abhishek/mine/apache/8282/docs/qlio/qlgit/ql.io/modules/
engine/lib/engine.js:357:41
   at /home/abhishek/mine/apache/8282/docs/qlio/qlgit/ql.io/modules/
engine/lib/engine.js:425:13

**Comment by s3u** [comment]
I've a fix. Adding some tests now.

**Comment by s3u** [comment]
There were three problems:
1. Default empty response bubbled up in corner cases was invalid. This caused the original stack above.
2. URI template validation was not failing a case like
   create table test on select get from 'http://localhost:8888/param={^id}'; 
   select \* from test where id in ('{arr}'); 
   as `{arr}` gets resolved to an array `[]`. This lead to the corner case in (1).
3. I forgot to checkin the peg change with https://github.com/ql-io/ql.io/commit/a574afe3defaf4d6b72d855345b857eceacf4919#modules/uri-template/lib/uri-template.js. Fixed now.

**Comment by s3u** [comment]
https://github.com/ql-io/ql.io/pull/342 has a fix.
