### ISSUE TITLE
EINVAL thrown under load.

### ISSUE THREAD

**Issue by prabhakhar** [ql-io/ql.io#518]
https://github.com/ql-io/ql.io/blob/master/modules/engine/lib/engine/source/verb.js#L83

Error: EINVAL, Incomplete character sequence.
    at /home/qlio/apps/PRM_Sidebar_QLIO/node_modules/ql.io-ebay-app/node_modules/ql.io-app/node_modules/ql.io-console/node_modules/ql.io-engine/lib/engine/source/verb.js:83:26
    at Array.forEach (native)
    at Function.<anonymous> (/home/qlio/apps/PRM_Sidebar_QLIO/node_modules/underscore/underscore.js:76:11)
    at Object.parse response (/home/qlio/apps/PRM_Sidebar_QLIO/node_modules/ql.io-ebay-app/node_modules/ql.io-app/node_modules/ql.io-console/node_modules/ql.io-engine/lib/engine/source/verb.js:82:11)
    at Object.parseResponse (/home/qlio/apps/PRM_Sidebar_QLIO/node_modules/ql.io-ebay-app/node_modules/ql.io-app/node_modules/ql.io-console/node_modules/ql.io-engine/lib/engine/source/verb.js:232:37)
    at Object.parseResponse (/home/qlio/apps/PRM_Sidebar_QLIO/node_modules/ql.io-ebay-app/node_modules/ql.io-app/node_modules/ql.io-console/node_modules/ql.io-engine/lib/engine/http/response.js:29:32)
    at IncomingMessage.<anonymous> (/home/qlio/apps/PRM_Sidebar_QLIO/node_modules/ql.io-ebay-app/node_modules/ql.io-app/node_modules/ql.io-console/node_modules/ql.io-engine/lib/engine/http/request.js:306:35)
    at IncomingMessage.emit (events.js:88:20)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:130:23)
    at Socket.socketOnData [as ondata](http.js:1288:20)

**Comment by s3u** [comment]
Parsing incomplete responses?

**Comment by idralyuk** [comment]
Dropped connections?

**Comment by s3u** [comment]
But dropped connections will cause partial responses, and should force node's http parser to raise an error.
