### ISSUE TITLE
Does not work with node 0.10

### ISSUE THREAD

**Issue by galniv** [ql-io/ql.io#588]
ql.io does not appear to work properly with node 0.10.

Using the latest version of node (0.10.4), I followed the instructions to clone ql.io-template and install/run the stand alone server. The install process completed with a number of warnings:

```
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4","npm":"1.2.18"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4","npm":"1.2.18"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4","npm":"1.2.18"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4","npm":"1.2.18"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.4","npm":"1.2.18"})
```

When running the app using start.sh, the server started but issued more warnings:

```
TypeError: Cannot read property 'port' of null
    at Server.<anonymous> (cluster.js:570:30)
    at Server.g (events.js:175:14)
    at Server.EventEmitter.emit (events.js:117:20)
    at net.js:1034:10
    at process._tickCallback (node.js:415:13)
error: TypeError: Cannot read property 'port' of null
    at Server.<anonymous> (cluster.js:570:30)
    at Server.g (events.js:175:14)
    at Server.EventEmitter.emit (events.js:117:20)
    at net.js:1034:10
    at process._tickCallback (node.js:415:13)
Uncaught error
```

I then ran a simple script:

```
create table gravatar
on select get from 'http://www.gravatar.com/{^token}.json'
resultset 'entry' select * from gravatar where token='kinvey'
```

And received the following response:

``` json
{
    "headers": {
        "content-type": "application/json"
    },
    "body": {
        "html": {
            "xmlns": "http://www.w3.org/1999/xhtml",
            "xml:lang": "en",
            "lang": "en",
            "head": {
                "title": "400 - Bad Request"
            },
            "body": {
                "h1": "400 - Bad Request"
            }
        }
    },
    "emitted": true
}
```

Following the exact same steps with node 0.8.19 (starting from scratch in a clean directory), however, returns the proper response:

``` json
{
        "id": "30180231",
        "hash": "a7b9b661d5d4ababcc6d661de43d3f07",
        "requestHash": "kinvey",
        "profileUrl": "http://gravatar.com/kinvey",
        "preferredUsername": "kinvey",
        "thumbnailUrl": "http://0.gravatar.com/avatar/a7b9b661d5d4ababcc6d661de43d3f07",
        "photos": [
            {
                "value": "http://0.gravatar.com/avatar/a7b9b661d5d4ababcc6d661de43d3f07",
                "type": "thumbnail"
            }
        ],
        "name": [ ],
        "displayName": "kinvey",
        "urls": [ ]
}
```

**Comment by hochang** [comment]
Thanks for the feedback. This is an known issue. We don't have spent effort on node 0.10 yet, but this is definitely something we will do soon.

**Comment by ivanstoyanov** [comment]
Hi, any update?

**Comment by palnes** [comment]
I too am in need of a 0.10.x compatible version.

**Comment by sourcec0de** [comment]
+1
